// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    console.log('index started');
    return $(".title").fitText(1.0, {
      minFontSize: 50,
      maxFontSize: 75
    });
  });

}).call(this);
